### ISSUE TITLE
Images like logo and screenshot not working in production

### ISSUE THREAD

**Issue by b4shful** [Floorp-Projects/web#42]
Hi, I visited https://floorp.app to check it out and noticed your logos and screenshots aren't loading...
Seems broken on both /en and /jp (so probably broken on all versions of the site)

Using Firefox 126.0 for Arch Linux

![image](https://github.com/Floorp-Projects/web/assets/28313200/e10893c0-f89f-486d-8ccc-793a3d593a77)

## Some "Logs"
(ok I mean photos of the console and network view, sorry)
![image](https://github.com/Floorp-Projects/web/assets/28313200/7a3fd133-cc98-4df5-8ca0-9efbac726bcd)

![image](https://github.com/Floorp-Projects/web/assets/28313200/ea919151-65b9-49e5-acc4-f86d4560800e)

**Comment by b4shful** [comment]
Also ran a sanity check (in case it was on my end) using a tool that came up as the first Google result when searching "webpage screenshot online":
https://pikwy.com/web/66548f1affed5258f6500eb0

It appears the images are also 404-ing there too:

![image](https://github.com/Floorp-Projects/web/assets/28313200/06cc0221-324a-4a89-b612-7e16cdade472)

**Comment by regularentropy** [comment]
Thank you for reporting. We have a new site to be deployed at the end of this month, or at the beginning of next.

**Comment by regularentropy** [comment]
Fixed https://github.com/Floorp-Projects/web/pull/43
