### ISSUE TITLE
“MacOS” を修正したい

### ISSUE THREAD

**Issue by CutterKnife** [Floorp-Projects/web#48]
https://github.com/Floorp-Projects/web/pull/45 で修正したかったのですが、うまくいかなかったようなのでこちらで失礼します…

![IMG_9543](https://github.com/Floorp-Projects/web/assets/110194318/c067ae82-cf40-40c0-8e12-70abef62d9df)

https://support.apple.com/ja-jp/guide/applestyleguide/apsg72b28652/web によると、

> In general, use *macOS* to refer to the Mac operating system.
> Don’t use *Mac OS* to refer generically to the operating system.

とのことなので、現在の Download ページで使用されている “MacOS” は誤りです。

**Comment by regularentropy** [comment]
すでに 「dev 」ブランチで修正されている。

**Comment by regularentropy** [comment]
https://github.com/Floorp-Projects/web/pull/49

**Comment by CutterKnife** [comment]
失礼しました！！
