### ISSUE TITLE
Vulnerable package being used

### ISSUE THREAD

**Issue by TheChilledBuffalo** [Floorp-Projects/web#52]
The [braces](https://www.npmjs.com/package/braces) npm package has a high severity (7.5/10) vulnerability on versions prior to 3.0.3

The version currently being used is 3.0.2 

![image](https://github.com/user-attachments/assets/7c04234a-cc0b-4e9f-ae29-dc1de8c0f423)

https://github.com/advisories/GHSA-grv7-fg5c-xmjg

**Comment by regularentropy** [comment]
Thank you for the report!

I've decided to upgrade the entire dependency list.

Fixed in: https://github.com/Floorp-Projects/web/commit/562866a7d36d69914bf81fce6b21b32628a4dc42
