### ISSUE TITLE
Can the 2.8 MB hero image be replaced with a nice 154 KB webp file instead?

### ISSUE THREAD

**Issue by nul800sebastiaan** [Floorp-Projects/web#56]
This file is uncompressed on the home page: https://github.com/Floorp-Projects/web/commit/88349333a089fb50b1b220c3a8c308359d194906

A webp version at 80% quality looks just as great and will massively reduce unnecessary bandwidth waste: 

[hero-2.zip](https://github.com/user-attachments/files/16588781/hero-2.zip)

**Comment by nul800sebastiaan** [comment]
Also, since that's a 2 year old screenshot, might be good to use a new screenshot instead and optimize it nicely before publishing.

**Comment by regularentropy** [comment]
Hi! Thank you for the recommendation. 
I've updated both screenshots and the design of the rounding corners (so it will less cut the main screenshot)
The issues got resolved [here](https://github.com/Floorp-Projects/web/commit/bef0e4e1a72660a80cff26ff092d56f1a7df3117)

**Comment by nul800sebastiaan** [comment]
Thanks @regularentropy! From 2.8MB to 218KB is wonderful! 🏅
